"""initial_schema_v3

Revision ID: 2ef374a0880a
Revises: 
Create Date: 2026-09-30 20:53:37.619690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef374a0880a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_to_user_id'), 'cases', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_cases_beneficiary_id'), 'cases', ['beneficiary_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_beneficiary_id'), 'grievances', ['beneficiary_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_runs_beneficiary_id'), 'recommendation_runs', ['beneficiary_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('milestone_days', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('is_retained', sa.Boolean(), nullable=True),
    sa.Column('current_wage_band', sa.String(), nullable=True),
    sa.Column('job_relevance_to_training', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_case_id'), 'followups', ['case_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('pathway_type', sa.String(), nullable=False),
    sa.Column('fit_band', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('factor_scores', sa.JSON(), nullable=True),
    sa.Column('explanation_beneficiary', sa.Text(), nullable=False),
    sa.Column('explanation_counsellor', sa.Text(), nullable=True),
    sa.Column('counterfactual_hints', sa.JSON(), nullable=True),
    sa.Column('uncertainty_level', sa.String(), nullable=True),
    sa.Column('truth_state', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_beneficiary_id'), 'recommendations', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_recommendations_run_id'), 'recommendations', ['run_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('target_organization_id', sa.String(), nullable=True),
    sa.Column('referral_type', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sla_due_date', sa.DateTime(), nullable=True),
    sa.Column('blocker_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['target_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_case_id'), 'referrals', ['case_id'], unique=False)
    op.create_table('pathways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pathway_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathways_beneficiary_id'), 'pathways', ['beneficiary_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('competency_name', sa.String(), nullable=False),
    sa.Column('gap_severity', sa.String(), nullable=True),
    sa.Column('how_to_close', sa.String(), nullable=True),
    sa.Column('nos_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_recommendation_id'), 'skill_gaps', ['recommendation_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('pathway_id', sa.String(), nullable=True),
    sa.Column('outcome_type', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('wage_band_inr', sa.String(), nullable=True),
    sa.Column('retention_90d_verified', sa.Boolean(), nullable=True),
    sa.Column('retention_180d_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_beneficiary_id'), 'outcomes', ['beneficiary_id'], unique=False)
    op.create_table('pathway_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pathway_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathway_actions_pathway_id'), 'pathway_actions', ['pathway_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathway_actions_pathway_id'), table_name='pathway_actions')
    op.drop_table('pathway_actions')
    op.drop_index(op.f('ix_outcomes_beneficiary_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_skill_gaps_recommendation_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_pathways_beneficiary_id'), table_name='pathways')
    op.drop_table('pathways')
    op.drop_index(op.f('ix_referrals_case_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_recommendations_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_beneficiary_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_followups_case_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_recommendation_runs_beneficiary_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_grievances_beneficiary_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_cases_beneficiary_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to_user_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
