"""initial_schema_v3

Revision ID: 8f7083d5f517
Revises: 
Create Date: 2026-10-01 09:10:34.194407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7083d5f517'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_areas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_type', sa.String(), nullable=True),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_areas_code'), 'admin_areas', ['code'], unique=True)
    op.create_index(op.f('ix_admin_areas_name'), 'admin_areas', ['name'], unique=False)
    op.create_index(op.f('ix_admin_areas_parent_code'), 'admin_areas', ['parent_code'], unique=False)
    op.create_index(op.f('ix_admin_areas_state_code'), 'admin_areas', ['state_code'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('jurisdiction_code', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=True),
    sa.Column('raw_audio_retention_opt_in', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_beneficiary_id'), 'consents', ['beneficiary_id'], unique=False)
    op.create_table('local_economic_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intensity_score', sa.Float(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('freshness_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_economic_signals_district_code'), 'local_economic_signals', ['district_code'], unique=False)
    op.create_index(op.f('ix_local_economic_signals_sector'), 'local_economic_signals', ['sector'], unique=False)
    op.create_table('occupations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nco_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nco_division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupations_nco_code'), 'occupations', ['nco_code'], unique=True)
    op.create_index(op.f('ix_occupations_sector'), 'occupations', ['sector'], unique=False)
    op.create_index(op.f('ix_occupations_title'), 'occupations', ['title'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('jurisdiction_code', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_jurisdiction_code'), 'organizations', ['jurisdiction_code'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ministry', sa.String(), nullable=True),
    sa.Column('target_group', sa.String(), nullable=True),
    sa.Column('benefits_summary', sa.Text(), nullable=False),
    sa.Column('eligibility_rules', sa.JSON(), nullable=True),
    sa.Column('indicative_subsidy_percentage', sa.Float(), nullable=True),
    sa.Column('max_subsidy_amount_inr', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('source_citation', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_table('qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qp_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=False),
    sa.Column('awarding_body', sa.String(), nullable=True),
    sa.Column('validity_status', sa.String(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('min_education', sa.String(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('official_nqr_url', sa.String(), nullable=True),
    sa.Column('rpl_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_nsqf_level'), 'qualifications', ['nsqf_level'], unique=False)
    op.create_index(op.f('ix_qualifications_qp_code'), 'qualifications', ['qp_code'], unique=True)
    op.create_index(op.f('ix_qualifications_title'), 'qualifications', ['title'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('complexity_level', sa.Integer(), nullable=True),
    sa.Column('is_traditional_craft', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('update_frequency', sa.String(), nullable=True),
    sa.Column('freshness_sla_days', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('beneficiaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('village_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('is_shared_phone', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_district_code'), 'beneficiaries', ['district_code'], unique=False)
    op.create_index(op.f('ix_beneficiaries_full_name'), 'beneficiaries', ['full_name'], unique=False)
    op.create_index(op.f('ix_beneficiaries_phone'), 'beneficiaries', ['phone'], unique=False)
    op.create_index(op.f('ix_beneficiaries_state_code'), 'beneficiaries', ['state_code'], unique=False)
    op.create_index(op.f('ix_beneficiaries_user_id'), 'beneficiaries', ['user_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('jurisdiction_scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupation_qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_qualifications_occupation_id'), 'occupation_qualifications', ['occupation_id'], unique=False)
    op.create_index(op.f('ix_occupation_qualifications_qualification_id'), 'occupation_qualifications', ['qualification_id'], unique=False)
    op.create_table('occupation_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_skills_occupation_id'), 'occupation_skills', ['occupation_id'], unique=False)
    op.create_index(op.f('ix_occupation_skills_skill_id'), 'occupation_skills', ['skill_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('opportunity_type', sa.String(), nullable=True),
    sa.Column('nco_code', sa.String(), nullable=True),
    sa.Column('qualification_id', sa.String(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('worksite_address', sa.String(), nullable=True),
    sa.Column('monthly_wage_inr', sa.Integer(), nullable=True),
    sa.Column('is_wage_guaranteed', sa.Boolean(), nullable=True),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('is_accessible_workplace', sa.Boolean(), nullable=True),
    sa.Column('truth_state', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_district_code'), 'opportunities', ['district_code'], unique=False)
    op.create_index(op.f('ix_opportunities_nco_code'), 'opportunities', ['nco_code'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('qualification_competencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('nos_code', sa.String(), nullable=False),
    sa.Column('nos_title', sa.String(), nullable=False),
    sa.Column('competency_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_competencies_nos_code'), 'qualification_competencies', ['nos_code'], unique=False)
    op.create_index(op.f('ix_qualification_competencies_qualification_id'), 'qualification_competencies', ['qualification_id'], unique=False)
    op.create_table('skill_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('alias_text', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias_text'), 'skill_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    op.create_table('training_centers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('has_wheelchair_access', sa.Boolean(), nullable=True),
    sa.Column('has_women_hostel', sa.Boolean(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_centers_district_code'), 'training_centers', ['district_code'], unique=False)
    op.create_index(op.f('ix_training_centers_name'), 'training_centers', ['name'], unique=False)
    op.create_index(op.f('ix_training_centers_organization_id'), 'training_centers', ['organization_id'], unique=False)
    op.create_table('beneficiaries_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('proficiency_band', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('evidence_utterance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_skills_beneficiary_id'), 'beneficiaries_skills', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_skills_skill_id'), 'beneficiaries_skills', ['skill_id'], unique=False)
    op.create_table('beneficiary_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('aspirations', sa.JSON(), nullable=True),
    sa.Column('work_preferences', sa.JSON(), nullable=True),
    sa.Column('mobility', sa.JSON(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('accessibility', sa.JSON(), nullable=True),
    sa.Column('household_context', sa.JSON(), nullable=True),
    sa.Column('financial_context', sa.JSON(), nullable=True),
    sa.Column('language_preferences', sa.JSON(), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_to_user_id'), 'cases', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_cases_beneficiary_id'), 'cases', ['beneficiary_id'], unique=False)
    op.create_table('enterprise_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('activity_title', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('indicative_startup_capital_inr', sa.Integer(), nullable=True),
    sa.Column('indicative_working_capital_inr', sa.Integer(), nullable=True),
    sa.Column('assumed_break_even_months', sa.Integer(), nullable=True),
    sa.Column('equipment_needed', sa.JSON(), nullable=True),
    sa.Column('target_customers', sa.JSON(), nullable=True),
    sa.Column('finance_schemes_considered', sa.JSON(), nullable=True),
    sa.Column('counsellor_id', sa.String(), nullable=True),
    sa.Column('counsellor_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_plans_beneficiary_id'), 'enterprise_plans', ['beneficiary_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_beneficiary_id'), 'grievances', ['beneficiary_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_runs_beneficiary_id'), 'recommendation_runs', ['beneficiary_id'], unique=False)
    op.create_table('training_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('center_id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=True),
    sa.Column('is_verified_live_batch', sa.Boolean(), nullable=True),
    sa.Column('truth_state', sa.String(), nullable=True),
    sa.Column('seat_capacity', sa.Integer(), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('fee_type', sa.String(), nullable=True),
    sa.Column('stipend_details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['training_centers.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_options_center_id'), 'training_options', ['center_id'], unique=False)
    op.create_index(op.f('ix_training_options_qualification_id'), 'training_options', ['qualification_id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('informal_sector', sa.String(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('tasks_performed', sa.JSON(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('materials_handled', sa.JSON(), nullable=True),
    sa.Column('responsibility_level', sa.String(), nullable=True),
    sa.Column('raw_utterance', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_beneficiary_id'), 'work_experiences', ['beneficiary_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=True),
    sa.Column('training_option_id', sa.String(), nullable=True),
    sa.Column('application_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['training_option_id'], ['training_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_beneficiary_id'), 'applications', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_training_option_id'), 'applications', ['training_option_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('milestone_days', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('is_retained', sa.Boolean(), nullable=True),
    sa.Column('current_wage_band', sa.String(), nullable=True),
    sa.Column('job_relevance_to_training', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_case_id'), 'followups', ['case_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('occupation_id', sa.String(), nullable=False),
    sa.Column('qualification_id', sa.String(), nullable=False),
    sa.Column('pathway_type', sa.String(), nullable=False),
    sa.Column('fit_band', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('factor_scores', sa.JSON(), nullable=True),
    sa.Column('explanation_beneficiary', sa.Text(), nullable=False),
    sa.Column('explanation_counsellor', sa.Text(), nullable=True),
    sa.Column('counterfactual_hints', sa.JSON(), nullable=True),
    sa.Column('uncertainty_level', sa.String(), nullable=True),
    sa.Column('truth_state', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_beneficiary_id'), 'recommendations', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_recommendations_run_id'), 'recommendations', ['run_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('target_organization_id', sa.String(), nullable=True),
    sa.Column('referral_type', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sla_due_date', sa.DateTime(), nullable=True),
    sa.Column('blocker_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['target_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_case_id'), 'referrals', ['case_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_skill_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('verified_by_user_id', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_skill_id'], ['beneficiaries_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_evidence_beneficiary_skill_id'), 'skill_evidence', ['beneficiary_skill_id'], unique=False)
    op.create_table('pathways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pathway_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathways_beneficiary_id'), 'pathways', ['beneficiary_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('competency_name', sa.String(), nullable=False),
    sa.Column('gap_severity', sa.String(), nullable=True),
    sa.Column('how_to_close', sa.String(), nullable=True),
    sa.Column('nos_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_recommendation_id'), 'skill_gaps', ['recommendation_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('beneficiary_id', sa.String(), nullable=False),
    sa.Column('pathway_id', sa.String(), nullable=True),
    sa.Column('outcome_type', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('wage_band_inr', sa.String(), nullable=True),
    sa.Column('retention_90d_verified', sa.Boolean(), nullable=True),
    sa.Column('retention_180d_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_beneficiary_id'), 'outcomes', ['beneficiary_id'], unique=False)
    op.create_table('pathway_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pathway_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathway_actions_pathway_id'), 'pathway_actions', ['pathway_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathway_actions_pathway_id'), table_name='pathway_actions')
    op.drop_table('pathway_actions')
    op.drop_index(op.f('ix_outcomes_beneficiary_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_skill_gaps_recommendation_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_pathways_beneficiary_id'), table_name='pathways')
    op.drop_table('pathways')
    op.drop_index(op.f('ix_skill_evidence_beneficiary_skill_id'), table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index(op.f('ix_referrals_case_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_recommendations_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_beneficiary_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_followups_case_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_applications_training_option_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_beneficiary_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_work_experiences_beneficiary_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_training_options_qualification_id'), table_name='training_options')
    op.drop_index(op.f('ix_training_options_center_id'), table_name='training_options')
    op.drop_table('training_options')
    op.drop_index(op.f('ix_recommendation_runs_beneficiary_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_grievances_beneficiary_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_enterprise_plans_beneficiary_id'), table_name='enterprise_plans')
    op.drop_table('enterprise_plans')
    op.drop_index(op.f('ix_cases_beneficiary_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to_user_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('beneficiary_profiles')
    op.drop_index(op.f('ix_beneficiaries_skills_skill_id'), table_name='beneficiaries_skills')
    op.drop_index(op.f('ix_beneficiaries_skills_beneficiary_id'), table_name='beneficiaries_skills')
    op.drop_table('beneficiaries_skills')
    op.drop_index(op.f('ix_training_centers_organization_id'), table_name='training_centers')
    op.drop_index(op.f('ix_training_centers_name'), table_name='training_centers')
    op.drop_index(op.f('ix_training_centers_district_code'), table_name='training_centers')
    op.drop_table('training_centers')
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias_text'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_qualification_competencies_qualification_id'), table_name='qualification_competencies')
    op.drop_index(op.f('ix_qualification_competencies_nos_code'), table_name='qualification_competencies')
    op.drop_table('qualification_competencies')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_nco_code'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_district_code'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_occupation_skills_skill_id'), table_name='occupation_skills')
    op.drop_index(op.f('ix_occupation_skills_occupation_id'), table_name='occupation_skills')
    op.drop_table('occupation_skills')
    op.drop_index(op.f('ix_occupation_qualifications_qualification_id'), table_name='occupation_qualifications')
    op.drop_index(op.f('ix_occupation_qualifications_occupation_id'), table_name='occupation_qualifications')
    op.drop_table('occupation_qualifications')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_beneficiaries_user_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_state_code'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_phone'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_full_name'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_district_code'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_qualifications_title'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_qp_code'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_nsqf_level'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_jurisdiction_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_occupations_title'), table_name='occupations')
    op.drop_index(op.f('ix_occupations_sector'), table_name='occupations')
    op.drop_index(op.f('ix_occupations_nco_code'), table_name='occupations')
    op.drop_table('occupations')
    op.drop_index(op.f('ix_local_economic_signals_sector'), table_name='local_economic_signals')
    op.drop_index(op.f('ix_local_economic_signals_district_code'), table_name='local_economic_signals')
    op.drop_table('local_economic_signals')
    op.drop_index(op.f('ix_consents_beneficiary_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_admin_areas_state_code'), table_name='admin_areas')
    op.drop_index(op.f('ix_admin_areas_parent_code'), table_name='admin_areas')
    op.drop_index(op.f('ix_admin_areas_name'), table_name='admin_areas')
    op.drop_index(op.f('ix_admin_areas_code'), table_name='admin_areas')
    op.drop_table('admin_areas')
    # ### end Alembic commands ###
